### ISSUE TITLE
Atropos module base class doesn't evaluate properly after merging

### ISSUE THREAD

**Issue by tanaes** [jdidion/atropos-multiqc#1]
I went ahead and added your code from this independent module library to my fork of the main MultiQC repo [here](https://github.com/tanaes/MultiQC/tree/atropos). 

Also added a set of some example test data to a branch of [MultiQC_TestData](https://github.com/tanaes/MultiQC_TestData/tree/atropos). 

Running with a Python2-based MultiQC installation doesn't seem to work properly, I think because there's a new-style vs old-style class problem with `super()`:

```
[ERROR  ]         multiqc : Oops! The 'atropos_post' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module atropos_post raised an exception: Traceback (most recent call last):
  File "/Users/jonsanders/Development/git_sw/MultiQC/scripts/multiqc", line 412, in multiqc
    output = mod()
  File "/Users/jonsanders/Development/git_sw/MultiQC/multiqc/modules/atropos/atropos.py", line 380, in __init__
    super().__init__(phase='Post', **kwargs)
TypeError: super() takes at least 1 argument (0 given)
============================================================
```

I can get it to run and generate a report with Python3-based installation, but none of the plots actually show up. I'm getting the section headings (and subheadings for the Stats modules), but no content. 

Any ideas?

**Comment by tanaes** [comment]
Updated with report screenshot:

![screenshot](https://user-images.githubusercontent.com/8292608/30764423-c53bf2d4-9f9f-11e7-82ef-a1be04963bde.png)
